version: '3.8'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 edm_user.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /path/to/your/static:/app/static
      - /path/to/your/media:/app/media
    depends_on:
      - web

  db:
    image: mysql:8.0.20
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: user_service
      MYSQL_USER: user_service
      MYSQL_PASSWORD: aivle
      MYSQL_ROOT_PASSWORD: aivle  # 여기는 MySQL의 root 비밀번호 설정

volumes:
  mysql_data: