pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Git 리포지토리에서 코드 체크아웃
                checkout scm
            }
        }
        stage('Build and Deploy') {
            steps {
                // Docker Compose를 사용하여 서비스 빌드 및 배포
                sh 'docker-compose up -d --build'
            }
        }
    }
}