# Generated by Django 4.2 on 2023-12-19 04:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(default="", max_length=100, unique=True)),
                ("name", models.CharField(default="", max_length=10)),
                ("birthdate", models.DateField()),
                (
                    "active_level",
                    models.CharField(
                        choices=[
                            ("level 1", "1레벨"),
                            ("level 2", "2레벨"),
                            ("level 3", "3레벨"),
                            ("level 4", "4레벨"),
                            ("level 5", "5레벨"),
                        ],
                        default="level 1",
                        max_length=7,
                    ),
                ),
                ("height", models.CharField(default=0, max_length=7)),
                ("weight", models.CharField(default=0, max_length=7)),
                (
                    "diet_purpose",
                    models.CharField(
                        choices=[
                            ("loss_weight", "체중 감량"),
                            ("keep_weight", "체중 유지"),
                            ("gain_weight", "체중 증량"),
                        ],
                        default="체중 유지",
                        max_length=11,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
