# Generated by Django 4.2 on 2023-12-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_birthdate_alter_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("man", "남자"), ("woman", "여자")], default="남자", max_length=5
            ),
        ),
    ]
