# Generated by Django 4.2 on 2023-12-20 01:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
    ]
