# Generated by Django 4.2 on 2023-12-20 01:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_remove_user_is_staff"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
