# Generated by Django 4.2 on 2023-12-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.SmallIntegerField(default=0),
        ),
    ]
