# Generated by Django 4.2 on 2023-12-20 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_alter_user_height_alter_user_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
