# Generated by Django 4.2 on 2023-12-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_alter_user_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="diet_purpose",
            field=models.CharField(
                choices=[
                    ("loss weight", "체중 감량"),
                    ("keep weight", "체중 유지"),
                    ("gain weight", "체중 증량"),
                ],
                default="체중 유지",
                max_length=11,
            ),
        ),
    ]
