# Generated by Django 4.2 on 2023-12-27 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscribe", "0003_alter_subscribe_subscribe_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="subscribe_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_subscribe",
                to=settings.AUTH_USER_MODEL,
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="subscribe_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_subscribe",
                to=settings.AUTH_USER_MODEL,
                to_field="uuid",
            ),
        ),
    ]
