# Generated by Django 4.2 on 2023-12-28 05:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscribe", "0004_alter_subscribe_subscribe_from_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscribe",
            unique_together={("subscribe_from", "subscribe_to")},
        ),
    ]
