# Generated by Django 4.2 on 2023-12-27 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "food_name",
                    models.CharField(
                        blank=True, db_column="Food_Name", max_length=45, null=True
                    ),
                ),
                ("weight_g", models.FloatField(blank=True, null=True)),
                (
                    "energy_kcal",
                    models.FloatField(blank=True, db_column="Energy_kcal", null=True),
                ),
                ("carbs_g", models.FloatField(blank=True, null=True)),
                ("sugar_g", models.FloatField(blank=True, null=True)),
                ("fat_g", models.FloatField(blank=True, null=True)),
                ("protein_g", models.FloatField(blank=True, null=True)),
                ("nat_mg", models.FloatField(blank=True, null=True)),
                ("col_mg", models.FloatField(blank=True, null=True)),
                ("nutrient_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "nutrient",
            },
        ),
        migrations.CreateModel(
            name="Usermeal",
            fields=[
                ("usermeal_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("meal_type", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(blank=True, null=True)),
                ("image_link", models.TextField(blank=True, null=True)),
                ("food_name", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "usermeal",
            },
        ),
        migrations.CreateModel(
            name="Usermealevaluation",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("meal_date", models.DateField(blank=True, null=True)),
                ("sys_config", models.FloatField(blank=True, null=True)),
                ("sum_carb", models.FloatField(blank=True, null=True)),
                ("sum_sugar", models.FloatField(blank=True, null=True)),
                ("sum_protein", models.FloatField(blank=True, null=True)),
                ("sun_fat", models.FloatField(blank=True, null=True)),
                ("meal_evaluation", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "usermealevaluation",
            },
        ),
        migrations.CreateModel(
            name="Usermealnutrientlink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Meal_Date.nutrient",
                    ),
                ),
                (
                    "usermeal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Meal_Date.usermeal",
                    ),
                ),
            ],
            options={
                "db_table": "usermealnutrientlink",
                "unique_together": {("usermeal", "nutrient")},
            },
        ),
    ]
